seed: 42
data:
  dataset: amazon
  data_dir: data_new/amazon
  profile_path: data_new/amazon/itm_prf.pkl
  min_user_interactions: 5
  min_item_interactions: 5
lightgcn:
  embedding_dim: 64
  n_layers: 3
pretrain:
  epochs: 1000
  batch_size: 1024
  lr: 0.001
  weight_decay: 0
  device: cuda
  num_workers: 8
  reg: 1e-4
  save_path: checkpoints/lightgcn_best_amazon_pretrain.pth
train:
  epochs: 1000
  batch_size: 1024
  lr: 0.0001
  weight_decay: 0
  device: cuda
  num_workers: 8
  reg: 1e-4
  save_path: checkpoints/lightgcn_best_amazon.pth
